In [5]:
import pandas as pd
import requests

In [8]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=95a16a77152360d16ac0d2a2d1928328&language=en-US&page=1')

In [19]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [20]:
df = pd.DataFrame()

In [21]:
df

Empty DataFrame
Columns: []
Index: []

In [26]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=95a16a77152360d16ac0d2a2d1928328&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = pd.concat([df,temp_df],ignore_index=True)

In [27]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1560520,Batman: Knightfall Part 1: Knightfall,"Arkham Asylum has been destroyed, and all its ...",2026-06-23,77.2879,9.189,338
1,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,85.6244,9.144,1153
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,41.5270,8.869,2185
3,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,16.6243,8.800,381
4,1621552,Facing El Chapo,Two Mexican officers must survive the final ho...,2026-08-21,102.8604,8.832,726
...,...,...,...,...,...,...,...
8555,2268,The Golden Compass,"In a parallel universe, after overhearing a sh...",2007-12-04,10.8359,6.100,4933
8556,427900,Home Again,Life for a single mom in Los Angeles takes an ...,2017-09-07,7.3809,6.086,1254
8557,370978,Kiki: Love to Love,"Through five stories, the movie addresses sex ...",2016-04-01,3.3885,6.085,387
8558,36670,Never Say Never Again,James Bond returns as the secret agent 007 to ...,1983-10-07,9.9556,6.085,1679
8559,1613,The 51st State,An American master chemist plans to score big ...,2001-12-07,5.6192,6.085,695

In [28]:
df.to_csv('movie.csv')